version: '3'
services:
  web:
    image: nginx:1.23.1
    # ホスト名を明示的に指定する
    hostname: web_pathy
    volumes:
      #設定ファイル
      - ./web/conf/:/etc/nginx/conf.d
      #ログ
      #- ./web/log/nginx/:/var/log/nginx/
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      #staticファイル
      - ./static:/static
    ports:
      - "8000:8000" #ポート指定、ホスト:コンテナ
    depends_on:
      - app  #appに依存

  db:
    image: mariadb:10.8.3
    # ホスト名を明示的に指定する
    hostname: db_pathy
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  #実行時のコマンド
    ports:
      - "3306:3306" #ポート指定、ホスト:コンテナ
    environment:  #コンテナ内の環境変数を指定
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pathy
      MYSQL_USER: pathy
      MYSQL_PASSWORD: panda5656
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql/:/var/lib/mysql/
      #- ./db/log/mysql/:/var/log/mysql/
  
  app:
    build: ./app
    # ホスト名を明示的に指定する
    hostname: app_pathy
    command: uwsgi --ini /etc/nginx/uwsgi.ini
    volumes: 
      - ./app:/opt/pathy
      - ./static:/static
      - ./web/uwsgi.ini:/etc/nginx/uwsgi.ini
    expose:
      - "8001"
    depends_on:
      - db  #dbに依存